//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureRef) DeepCopyInto(out *FeatureRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureRef.
func (in *FeatureRef) DeepCopy() *FeatureRef {
	if in == nil {
		return nil
	}
	out := new(FeatureRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureDeprecationSpec) DeepCopyInto(out *FeatureDeprecationSpec) {
	*out = *in
	in.Feature.DeepCopyInto(&out.Feature)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureDeprecationSpec.
func (in *FeatureDeprecationSpec) DeepCopy() *FeatureDeprecationSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureDeprecationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureDeprecationStatus) DeepCopyInto(out *FeatureDeprecationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureDeprecationStatus.
func (in *FeatureDeprecationStatus) DeepCopy() *FeatureDeprecationStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureDeprecationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureDeprecation) DeepCopyInto(out *FeatureDeprecation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureDeprecation.
func (in *FeatureDeprecation) DeepCopy() *FeatureDeprecation {
	if in == nil {
		return nil
	}
	out := new(FeatureDeprecation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureDeprecation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureDeprecationList) DeepCopyInto(out *FeatureDeprecationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeatureDeprecation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureDeprecationList.
func (in *FeatureDeprecationList) DeepCopy() *FeatureDeprecationList {
	if in == nil {
		return nil
	}
	out := new(FeatureDeprecationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureDeprecationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
